#In this yaml file we are defining the column name as well as dtype of it (for validating Dataset)
#along with mentioning the target column!!
Columns:
  fixed acidity: float64
  volatile acidity: float64
  citric acid: float64
  residual sugar: flaot64
  free sulfur dioxide: float64
  total sulfur dioxide: float64
  density: float64
  pH: float64
  sulphates: float64
  alcohol: float64
  quality: int64
  Id: int64


target_column:
  quality: int64