artifacts_root: artifacts

#first Step we are doing is Data ingestion -->
#location/source where data can be store such server,cloud,database ..etc we have to fetch the data from that source store into specific location mentioned in yaml file!!
data_ingestion:
  root_dir_path: artifacts/data_ingestion
  Zip_local_dir_path: artifacts/data_ingestion/
  unzip_dir_path: artifacts/data_ingestion/
  train_test_path: artifacts/data_ingestion/


#step2:- Here we are doing Data Validations means checking schemal.yaml file column exist in csv or not
data_validation:
  root_dir_path: artifacts/data_validation
  unzip_data_dir_path:  artifacts/data_ingestion/WineQT.csv #yaha se csv file ley kar data validate karo
  status_file: artifacts/data_validation/status.txt

#step3:- Here we are doing Data Transformation 
data_transformation:
  root_dir_path: artifacts/data_transformation
  save_obj_dirpath: artifacts/data_transformation/preprocessor.pkl
  csv_dir_path: artifacts/data_ingestion/ #yaha se csv file ley kar data transformation doing


